/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_api_foods_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/nickname/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll Nickname
         * @description One candidate. Called repeatedly during registration; commits nothing.
         */
        post: operations["roll_nickname_api_profile_nickname_roll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_profile_patch"];
        trace?: never;
    };
    "/api/profile/coaching-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coaching History */
        get: operations["coaching_history_api_profile_coaching_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Meals */
        get: operations["recent_meals_api_logs_meals_get"];
        put?: never;
        /** Log Meal */
        post: operations["log_meal_api_logs_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Summary */
        get: operations["daily_summary_api_summary_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Day Type */
        put: operations["set_day_type_api_days_type_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Weight */
        post: operations["log_weight_api_logs_weight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Goal Phase */
        post: operations["set_goal_phase_api_goals_phase_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Revise Goal Phase */
        patch: operations["revise_goal_phase_api_goals_phase_patch"];
        trace?: never;
    };
    "/api/goals/phase/{phase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Goal Phase */
        delete: operations["delete_goal_phase_api_goals_phase__phase_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goal Phases */
        get: operations["list_goal_phases_api_goals_phases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Activities */
        get: operations["search_activities_api_activities_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/exercise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Exercise */
        post: operations["log_exercise_api_logs_exercise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/exercise/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Exercise */
        delete: operations["delete_exercise_api_logs_exercise__log_id__delete"];
        options?: never;
        head?: never;
        /** Revise Exercise */
        patch: operations["revise_exercise_api_logs_exercise__log_id__patch"];
        trace?: never;
    };
    "/api/logs/meals/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Log */
        delete: operations["delete_log_api_logs_meals__log_id__delete"];
        options?: never;
        head?: never;
        /** Revise Log */
        patch: operations["revise_log_api_logs_meals__log_id__patch"];
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        /** Save Template */
        post: operations["save_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Revise Template */
        patch: operations["revise_template_api_templates__template_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOut */
        ActivityOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Met */
            met: number;
        };
        /** ActivitySearchResponse */
        ActivitySearchResponse: {
            /** Results */
            results: components["schemas"]["ActivityOut"][];
            server_time: components["schemas"]["ServerTime"];
        };
        /** ClosedPhaseOut */
        ClosedPhaseOut: {
            /** Phase Id */
            phase_id: number;
            /** End Date */
            end_date: string;
        };
        /** CoachingHistoryResponse */
        CoachingHistoryResponse: {
            /** Revisions */
            revisions: components["schemas"]["CoachingRevisionOut"][];
            server_time: components["schemas"]["ServerTime"];
        };
        /** CoachingRevisionOut */
        CoachingRevisionOut: {
            /** Notes */
            notes: string | null;
            /** Set At */
            set_at: string;
        };
        /** DailySummaryResponse */
        DailySummaryResponse: {
            /** Date */
            date: string;
            /** Day Type */
            day_type: string;
            /** Day Type Source */
            day_type_source: string;
            totals: components["schemas"]["DayTotals"];
            target: components["schemas"]["TargetOut"] | null;
            remaining: components["schemas"]["RemainingOut"] | null;
            /** Meals */
            meals: components["schemas"]["SummaryMealOut"][];
            /** Exercise */
            exercise: components["schemas"]["SummaryExerciseOut"][];
            profile_context: components["schemas"]["ProfileContextOut"];
            server_time: components["schemas"]["ServerTime"];
        };
        /** DayTotals */
        DayTotals: {
            /** Local Date */
            local_date: string;
            /** Items Logged */
            items_logged: number;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /** DayTypeResponse */
        DayTypeResponse: {
            /** Date */
            date: string;
            /** Day Type */
            day_type: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** DayTypeSet */
        DayTypeSet: {
            /** Day Type */
            day_type: string;
            /**
             * Date
             * @description Only when the user stated a day; defaults to today.
             */
            date?: string | null;
        };
        /** ExerciseDeletedResponse */
        ExerciseDeletedResponse: {
            /** Deleted Log Id */
            deleted_log_id: number;
            /** Date */
            date: string;
            /** Day Type */
            day_type: string;
            /** Day Type Source */
            day_type_source: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** ExerciseLogCreate */
        ExerciseLogCreate: {
            /** Kind */
            kind: string;
            /** Activity Id */
            activity_id?: number | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Sets */
            sets?: components["schemas"]["StrengthSetIn"][] | null;
            /**
             * Ts
             * @description Only when the user stated a time. Omitted means server now().
             */
            ts?: string | null;
            /**
             * Planned
             * @default false
             */
            planned: boolean;
            /**
             * Source
             * @default user
             */
            source: string;
            /** Notes */
            notes?: string | null;
        };
        /** ExerciseLogResponse */
        ExerciseLogResponse: {
            /** Log Id */
            log_id: number;
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            activity: components["schemas"]["ActivityOut"] | null;
            /** Duration Min */
            duration_min: number | null;
            /** Kcal Estimate */
            kcal_estimate: number | null;
            /** Planned */
            planned: boolean;
            /** Source */
            source: string;
            /** Notes */
            notes: string | null;
            /** Sets */
            sets: components["schemas"]["StrengthSetOut"][];
            /** Date */
            date: string;
            /** Day Type */
            day_type: string;
            /** Day Type Source */
            day_type_source: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** ExerciseLogRevise */
        ExerciseLogRevise: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
        };
        /** FoodCandidateOut */
        FoodCandidateOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Language */
            name_language: string;
            /** Source */
            source: string;
            /** Owned */
            owned: boolean;
            per_100g: components["schemas"]["Per100g"];
            /** Serving Units */
            serving_units: components["schemas"]["ServingUnitOut"][];
        };
        /** FoodSearchResponse */
        FoodSearchResponse: {
            /** Results */
            results: components["schemas"]["FoodCandidateOut"][];
            /** Language */
            language: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** GoalHistoryResponse */
        GoalHistoryResponse: {
            /** Phases */
            phases: components["schemas"]["GoalPhaseOut"][];
            server_time: components["schemas"]["ServerTime"];
        };
        /** GoalPhaseCreate */
        GoalPhaseCreate: {
            /** Kind */
            kind: string;
            /** Kcal Training */
            kcal_training: number;
            /** Kcal Rest */
            kcal_rest: number;
            /** Protein Training */
            protein_training: number;
            /** Protein Rest */
            protein_rest: number;
            /** Rate Target */
            rate_target?: number | null;
            /** Start Date */
            start_date?: string | null;
        };
        /** GoalPhaseDeletedResponse */
        GoalPhaseDeletedResponse: {
            /** Deleted Phase Id */
            deleted_phase_id: number;
            /** Kind */
            kind: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string | null;
            server_time: components["schemas"]["ServerTime"];
        };
        /** GoalPhaseOut */
        GoalPhaseOut: {
            /** Phase Id */
            phase_id: number;
            /** Kind */
            kind: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Kcal Target Training */
            kcal_target_training: number;
            /** Kcal Target Rest */
            kcal_target_rest: number;
            /** Protein Target Training */
            protein_target_training: number;
            /** Protein Target Rest */
            protein_target_rest: number;
            /** Rate Target Kg Per Week */
            rate_target_kg_per_week: number | null;
        };
        /** GoalPhaseResponse */
        GoalPhaseResponse: {
            /** Phase Id */
            phase_id: number;
            /** Kind */
            kind: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Kcal Target Training */
            kcal_target_training: number;
            /** Kcal Target Rest */
            kcal_target_rest: number;
            /** Protein Target Training */
            protein_target_training: number;
            /** Protein Target Rest */
            protein_target_rest: number;
            /** Rate Target Kg Per Week */
            rate_target_kg_per_week: number | null;
            server_time: components["schemas"]["ServerTime"];
            closed_previous?: components["schemas"]["ClosedPhaseOut"] | null;
        };
        /** GoalPhaseRevise */
        GoalPhaseRevise: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogDeletedResponse */
        LogDeletedResponse: {
            /** Deleted Log Id */
            deleted_log_id: number;
            day_totals: components["schemas"]["DayTotals"];
            server_time: components["schemas"]["ServerTime"];
        };
        /** LoggedItemOut */
        LoggedItemOut: {
            /** Food Id */
            food_id: number;
            /** Grams */
            grams: number;
            /** Kcal */
            kcal: number | null;
            /** Protein G */
            protein_g: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Fiber G */
            fiber_g: number | null;
        };
        /** MealItem */
        MealItem: {
            /** Food Id */
            food_id: number;
            /** Grams */
            grams: number;
        };
        /** MealLogCreate */
        MealLogCreate: {
            /** Items */
            items: (components["schemas"]["MealItem"] | components["schemas"]["TemplateRef"])[];
            /** Meal */
            meal?: string | null;
            /**
             * Ts
             * @description Only when the user stated a time. Omitted means server now(). Naive timestamps are read in the profile timezone.
             */
            ts?: string | null;
            /**
             * Input Mode
             * @default text
             */
            input_mode: string;
            /** Notes */
            notes?: string | null;
        };
        /** MealLogResponse */
        MealLogResponse: {
            /** Log Id */
            log_id: number;
            /** Ts */
            ts: string;
            /** Meal */
            meal: string | null;
            /** Input Mode */
            input_mode: string;
            /** Planned */
            planned: boolean;
            /** Notes */
            notes: string | null;
            /** Items */
            items: components["schemas"]["LoggedItemOut"][];
            day_totals: components["schemas"]["DayTotals"];
            server_time: components["schemas"]["ServerTime"];
        };
        /** MealLogRevise */
        MealLogRevise: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
        };
        /** NicknameRollResponse */
        NicknameRollResponse: {
            /** Nickname */
            nickname: string;
        };
        /** Per100g */
        Per100g: {
            /** Kcal */
            kcal: number | null;
            /** Protein G */
            protein_g: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Fiber G */
            fiber_g: number | null;
        };
        /** ProfileContextOut */
        ProfileContextOut: {
            /** Dietary Prefs */
            dietary_prefs: {
                [key: string]: unknown;
            };
            /** Coaching Notes */
            coaching_notes: string | null;
        };
        /** ProfileCreate */
        ProfileCreate: {
            /**
             * Nickname
             * @description A candidate previously returned by /profile/nickname/roll. Omitted means take whatever the generator produces.
             */
            nickname?: string | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Nickname */
            nickname: string;
            /** Birth Year */
            birth_year: number | null;
            /** Height Cm */
            height_cm: number | null;
            /** Sex */
            sex: string | null;
            /** Activity Baseline */
            activity_baseline: string | null;
            /** Timezone */
            timezone: string;
            /** Units */
            units: string;
            /** Language */
            language: string;
            /** Ui Language */
            ui_language: string | null;
            /** Show Item Macros */
            show_item_macros: boolean;
            /** Dietary Prefs */
            dietary_prefs: {
                [key: string]: unknown;
            };
            /** Coaching Notes */
            coaching_notes: string | null;
            server_time: components["schemas"]["ServerTime"];
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
        };
        /** RecentMealOut */
        RecentMealOut: {
            /** Log Id */
            log_id: number;
            /** Date */
            date: string;
            /** Ts */
            ts: string;
            /** Meal */
            meal: string | null;
            /** Planned */
            planned: boolean;
            /** Notes */
            notes: string | null;
            /** Kcal */
            kcal: number;
            /** Items */
            items: components["schemas"]["SummaryItemOut"][];
        };
        /** RecentMealsResponse */
        RecentMealsResponse: {
            /** Days */
            days: number;
            /** Meals */
            meals: components["schemas"]["RecentMealOut"][];
            /** Language */
            language: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** RemainingOut */
        RemainingOut: {
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
        };
        /** ServerTime */
        ServerTime: {
            /** Utc */
            utc: string;
            /** Timezone */
            timezone: string;
            /** Local Date */
            local_date: string;
        };
        /** ServingUnitOut */
        ServingUnitOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Grams */
            grams: number;
        };
        /** StrengthSetIn */
        StrengthSetIn: {
            /** Exercise */
            exercise: string;
            /** Reps */
            reps: number;
            /**
             * Weight Kg
             * @description 0 is a bodyweight set.
             */
            weight_kg: number;
            /** Rpe */
            rpe?: number | null;
        };
        /** StrengthSetOut */
        StrengthSetOut: {
            /** Set No */
            set_no: number;
            /** Exercise */
            exercise: string | null;
            /** Reps */
            reps: number;
            /** Weight Kg */
            weight_kg: number;
            /** Rpe */
            rpe: number | null;
        };
        /** SummaryExerciseOut */
        SummaryExerciseOut: {
            /** Log Id */
            log_id: number;
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            activity: components["schemas"]["ActivityOut"] | null;
            /** Duration Min */
            duration_min: number | null;
            /** Kcal Estimate */
            kcal_estimate: number | null;
            /** Planned */
            planned: boolean;
            /** Source */
            source: string;
            /** Notes */
            notes: string | null;
            /** Sets */
            sets: components["schemas"]["StrengthSetOut"][];
        };
        /** SummaryItemOut */
        SummaryItemOut: {
            /** Food Id */
            food_id: number;
            /** Name */
            name: string | null;
            /** Source */
            source: string | null;
            /** Grams */
            grams: number;
            /** Kcal */
            kcal: number | null;
            /** Protein G */
            protein_g: number | null;
            /** Carbs G */
            carbs_g: number | null;
            /** Fat G */
            fat_g: number | null;
            /** Fiber G */
            fiber_g: number | null;
        };
        /** SummaryMealOut */
        SummaryMealOut: {
            /** Log Id */
            log_id: number;
            /** Ts */
            ts: string;
            /** Meal */
            meal: string | null;
            /** Planned */
            planned: boolean;
            /** Notes */
            notes: string | null;
            /** Kcal */
            kcal: number;
            /** Items */
            items: components["schemas"]["SummaryItemOut"][];
        };
        /** TargetOut */
        TargetOut: {
            /** Kind */
            kind: string;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Rate Kg Per Week */
            rate_kg_per_week: number | null;
        };
        /** TemplateCreate */
        TemplateCreate: {
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["TemplateItemIn"][];
            /** Total Grams */
            total_grams?: number | null;
        };
        /** TemplateDeletedResponse */
        TemplateDeletedResponse: {
            /** Deleted Template Id */
            deleted_template_id: number;
            server_time: components["schemas"]["ServerTime"];
        };
        /** TemplateItemIn */
        TemplateItemIn: {
            /** Food Id */
            food_id: number;
            /** Grams */
            grams: number;
        };
        /** TemplateItemOut */
        TemplateItemOut: {
            /** Food Id */
            food_id: number;
            /** Grams */
            grams: number;
        };
        /** TemplateListItemOut */
        TemplateListItemOut: {
            /** Food Id */
            food_id: number;
            /** Name */
            name: string | null;
            /** Grams */
            grams: number;
            per_100g: components["schemas"]["Per100g"];
            /** Kcal */
            kcal: number | null;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Template Id */
            template_id: number;
            /** Name */
            name: string;
            /** Total Grams */
            total_grams: number | null;
            /** Kcal */
            kcal: number | null;
            /** Use Count */
            use_count: number;
            /** Last Used At */
            last_used_at: string | null;
            /** Items */
            items: components["schemas"]["TemplateListItemOut"][];
        };
        /**
         * TemplateRef
         * @description A template standing in for its foods; expanded server-side at log time.
         */
        TemplateRef: {
            /** Template Id */
            template_id: number;
            /** Portions */
            portions?: number | null;
            /** Grams */
            grams?: number | null;
        };
        /** TemplateRevise */
        TemplateRevise: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
        };
        /** TemplateSavedResponse */
        TemplateSavedResponse: {
            /** Template Id */
            template_id: number;
            /** Name */
            name: string;
            /** Total Grams */
            total_grams: number | null;
            /** Created */
            created: boolean;
            /** Items */
            items: components["schemas"]["TemplateItemOut"][];
            server_time: components["schemas"]["ServerTime"];
        };
        /** TemplatesResponse */
        TemplatesResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateOut"][];
            /** Language */
            language: string;
            server_time: components["schemas"]["ServerTime"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightLogCreate */
        WeightLogCreate: {
            /** Weight Kg */
            weight_kg?: number | null;
            /**
             * Date
             * @description Only when the user stated a day; defaults to today.
             */
            date?: string | null;
            /** Waist Cm */
            waist_cm?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** WeightLogResponse */
        WeightLogResponse: {
            /** Date */
            date: string;
            /** Weight Kg */
            weight_kg: number | null;
            /** Waist Cm */
            waist_cm: number | null;
            /** Notes */
            notes: string | null;
            server_time: components["schemas"]["ServerTime"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_foods_api_foods_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roll_nickname_api_profile_nickname_roll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NicknameRollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coaching_history_api_profile_coaching_history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachingHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_meals_api_logs_meals_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentMealsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_meal_api_logs_meals_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_summary_api_summary_daily_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_day_type_api_days_type_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayTypeSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_weight_api_logs_weight_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeightLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_goal_phase_api_goals_phase_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalPhaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalPhaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_goal_phase_api_goals_phase_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalPhaseRevise"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalPhaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_phase_api_goals_phase__phase_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                phase_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalPhaseDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goal_phases_api_goals_phases_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_activities_api_activities_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_exercise_api_logs_exercise_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_api_logs_exercise__log_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_exercise_api_logs_exercise__log_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseLogRevise"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_log_api_logs_meals__log_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_log_api_logs_meals__log_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealLogRevise"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSavedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_template_api_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRevise"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSavedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
