"""Initial Annos schema: user_profile, foods, serving_units

Hand-written rather than autogenerated so the pg_trgm extension is created
before the indexes that depend on it, and so the enum type is created once
explicitly instead of implicitly by the first table that references it.

Revision ID: 0001
Revises:
Create Date: 2026-08-04

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Trigram search over food names. Requires privileges to create an extension —
# fine locally (the compose superuser) but in production the extension may need
# creating once by hand as a superuser before this migration runs.
_TRGM = "CREATE EXTENSION IF NOT EXISTS pg_trgm"

# Provenance values, stored as text with a CHECK rather than a native enum.
# A native postgresql.ENUM here emitted CREATE TYPE before *every*
# op.create_table in this migration (Alembic re-attaches an unbound enum to a
# fresh MetaData per call), which fails on the second. Text + CHECK also makes
# widening the set a one-line transactional migration.
FOOD_SOURCES = ("fineli", "verified", "user", "label", "ai_estimate")
FOOD_SOURCE_CHECK = "source IN ({})".format(", ".join(f"'{s}'" for s in FOOD_SOURCES))


def upgrade() -> None:
    op.execute(_TRGM)

    op.create_table(
        "user_profile",
        # The Better Auth user id. Opaque text, not a UUID, and deliberately not
        # a foreign key: this schema never references the auth tables.
        sa.Column("subject", sa.Text(), primary_key=True),
        sa.Column("nickname", sa.Text(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=16), nullable=True),
        sa.Column("activity_baseline", sa.String(length=16), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False, server_default="Europe/Helsinki"),
        sa.Column("units", sa.String(length=8), nullable=False, server_default="metric"),
        sa.Column(
            "dietary_prefs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("coaching_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("nickname", name="uq_user_profile_nickname"),
        sa.CheckConstraint(
            "sex IS NULL OR sex IN ('female', 'male', 'other')", name="ck_profile_sex"
        ),
        sa.CheckConstraint("units IN ('metric', 'imperial')", name="ck_profile_units"),
        sa.CheckConstraint(
            "birth_year IS NULL OR (birth_year BETWEEN 1900 AND 2100)",
            name="ck_profile_birth_year",
        ),
    )

    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_fi", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("fineli_id", sa.Integer(), nullable=True),
        # NULL = global (Fineli seed, verified entries). Set = private to that user.
        sa.Column("owner_id", sa.Text(), nullable=True),
        sa.Column("kcal", sa.Numeric(8, 2), nullable=False),
        sa.Column("protein_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("carbs_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("fat_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("fiber_g", sa.Numeric(8, 2), nullable=True),
        sa.Column(
            "micros",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("fineli_id", name="uq_foods_fineli_id"),
        sa.CheckConstraint(FOOD_SOURCE_CHECK, name="ck_foods_source"),
    )
    op.create_index("ix_foods_owner_id", "foods", ["owner_id"])
    op.create_index(
        "ix_foods_name_trgm",
        "foods",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_foods_name_fi_trgm",
        "foods",
        ["name_fi"],
        postgresql_using="gin",
        postgresql_ops={"name_fi": "gin_trgm_ops"},
    )

    op.create_table(
        "serving_units",
        sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("grams", sa.Numeric(8, 2), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("food_id", "name", name="uq_serving_units_food_name"),
    )


def downgrade() -> None:
    op.drop_table("serving_units")
    op.drop_index("ix_foods_name_fi_trgm", table_name="foods")
    op.drop_index("ix_foods_name_trgm", table_name="foods")
    op.drop_index("ix_foods_owner_id", table_name="foods")
    op.drop_table("foods")
    op.drop_table("user_profile")
    # pg_trgm is left in place: other things may rely on it, and dropping an
    # extension is not this migration's business to undo.
