"""Initial Annos schema: user_profile, foods, serving_units

Hand-written rather than autogenerated so the pg_trgm extension is created
before the indexes that depend on it, and so the enum type is created once
explicitly instead of implicitly by the first table that references it.

Revision ID: 0001
Revises:
Create Date: 2026-08-04

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Trigram search over food names. Requires privileges to create an extension —
# fine locally (the compose superuser) but in production the extension may need
# creating once by hand as a superuser before this migration runs.
_TRGM = "CREATE EXTENSION IF NOT EXISTS pg_trgm"

# Provenance, as a native Postgres enum.
#
# create_type=False stops op.create_table("foods") emitting its own CREATE TYPE;
# the explicit create() below is the single source of the statement, so the type
# exists before any table references it. Leaving create_type at its default here
# AND calling create() produces the type twice and fails with
# DuplicateObjectError — verify with `alembic upgrade head --sql` if you touch
# this: exactly one CREATE TYPE should appear.
FOOD_SOURCES = ("fineli", "verified", "user", "label", "ai_estimate")

food_source = postgresql.ENUM(*FOOD_SOURCES, name="food_source", create_type=False)


def upgrade() -> None:
    op.execute(_TRGM)
    food_source.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "user_profile",
        # The Better Auth user id. Opaque text, not a UUID, and deliberately not
        # a foreign key: this schema never references the auth tables.
        sa.Column("subject", sa.Text(), primary_key=True),
        sa.Column("nickname", sa.Text(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=16), nullable=True),
        sa.Column("activity_baseline", sa.String(length=16), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False, server_default="Europe/Helsinki"),
        sa.Column("units", sa.String(length=8), nullable=False, server_default="metric"),
        sa.Column(
            "dietary_prefs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("coaching_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("nickname", name="uq_user_profile_nickname"),
        sa.CheckConstraint(
            "sex IS NULL OR sex IN ('female', 'male', 'other')", name="ck_profile_sex"
        ),
        sa.CheckConstraint("units IN ('metric', 'imperial')", name="ck_profile_units"),
        sa.CheckConstraint(
            "birth_year IS NULL OR (birth_year BETWEEN 1900 AND 2100)",
            name="ck_profile_birth_year",
        ),
    )

    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_fi", sa.Text(), nullable=True),
        sa.Column("source", food_source, nullable=False),
        sa.Column("fineli_id", sa.Integer(), nullable=True),
        # NULL = global (Fineli seed, verified entries). Set = private to that user.
        sa.Column("owner_id", sa.Text(), nullable=True),
        sa.Column("kcal", sa.Numeric(8, 2), nullable=False),
        sa.Column("protein_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("carbs_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("fat_g", sa.Numeric(8, 2), nullable=False),
        sa.Column("fiber_g", sa.Numeric(8, 2), nullable=True),
        sa.Column(
            "micros",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("fineli_id", name="uq_foods_fineli_id"),
    )
    op.create_index("ix_foods_owner_id", "foods", ["owner_id"])
    op.create_index(
        "ix_foods_name_trgm",
        "foods",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_foods_name_fi_trgm",
        "foods",
        ["name_fi"],
        postgresql_using="gin",
        postgresql_ops={"name_fi": "gin_trgm_ops"},
    )

    op.create_table(
        "serving_units",
        sa.Column("id", sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("grams", sa.Numeric(8, 2), nullable=False),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("food_id", "name", name="uq_serving_units_food_name"),
    )


def downgrade() -> None:
    op.drop_table("serving_units")
    op.drop_index("ix_foods_name_fi_trgm", table_name="foods")
    op.drop_index("ix_foods_name_trgm", table_name="foods")
    op.drop_index("ix_foods_owner_id", table_name="foods")
    op.drop_table("foods")
    op.drop_table("user_profile")
    food_source.drop(op.get_bind(), checkfirst=True)
    # pg_trgm is left in place: other things may rely on it, and dropping an
    # extension is not this migration's business to undo.
