"""Meal templates: favourites and recipes as one loggable unit

`meal_templates` + `meal_template_items` store foods and grams only, never
macros — snapshots happen at log time so a template logged next month uses
that day's definitions. `total_grams` makes a template a recipe: the whole
batch weighs this much and logging takes a portion. Names are unique per
owner; re-saving a name replaces the contents.

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-06

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("total_grams", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_grams IS NULL OR total_grams > 0", name="ck_meal_templates_total_grams"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject", "name", name="uq_meal_templates_subject_name"),
    )
    op.create_table(
        "meal_template_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("grams", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.CheckConstraint("grams > 0", name="ck_meal_template_items_grams_positive"),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.ForeignKeyConstraint(["template_id"], ["meal_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_meal_template_items_template_id", "meal_template_items", ["template_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meal_template_items_template_id", table_name="meal_template_items")
    op.drop_table("meal_template_items")
    op.drop_table("meal_templates")
    # ### end Alembic commands ###
